name: dl2020
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - argon2-cffi=20.1.0=py37h8f50634_2
  - async_generator=1.10=py_0
  - attrs=20.2.0=pyh9f0ad1d_0
  - backcall=0.2.0=pyh9f0ad1d_0
  - backports=1.0=py_2
  - backports.functools_lru_cache=1.6.1=py_0
  - blas=1.0=mkl
  - bleach=3.2.1=pyh9f0ad1d_0
  - brotlipy=0.7.0=py37hb5d75c8_1001
  - ca-certificates=2020.6.20=hecda079_0
  - certifi=2020.6.20=py37he5f6b98_2
  - cffi=1.14.3=py37he30daa8_0
  - chardet=3.0.4=py37he5f6b98_1008
  - cryptography=3.1.1=py37hff6837a_1
  - cudatoolkit=10.1.243
  - decorator=4.4.2=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37hc8dfbb8_1002
  - freetype=2.10.4=h5ab3b9f_0
  - idna=2.10=pyh9f0ad1d_0
  - importlib-metadata=2.0.0=py_1
  - importlib_metadata=2.0.0=1
  - intel-openmp=2020.2=254
  - ipykernel=5.3.4=py37hc6149b9_1
  - ipython=7.18.1=py37hc6149b9_1
  - ipython_genutils=0.2.0=py_1
  - jedi=0.17.2=py37hc8dfbb8_1
  - jinja2=2.11.2=pyh9f0ad1d_0
  - jpeg=9b=h024ee3a_2
  - json5=0.9.5=pyh9f0ad1d_0
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.7=py_0
  - jupyter_core=4.6.3=py37hc8dfbb8_2
  - jupyterlab=2.2.8=py_0
  - jupyterlab_pygments=0.1.2=pyh9f0ad1d_0
  - jupyterlab_server=1.2.0=py_0
  - lcms2=2.11=h396b838_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20191231=h14c3975_1
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.18=h516909a_1
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - lz4-c=1.9.2=heb0550a_3
  - markupsafe=1.1.1=py37hb5d75c8_2
  - mistune=0.8.4=py37h8f50634_1002
  - mkl=2020.2=256
  - mkl-service=2.3.0=py37he904b0f_0
  - mkl_fft=1.2.0=py37h23d657b_0
  - mkl_random=1.1.1=py37h0573a6f_0
  - nbclient=0.5.1=py_0
  - nbconvert=6.0.7=py37hc8dfbb8_1
  - nbformat=5.0.8=py_0
  - ncurses=6.2=he6710b0_1
  - nest-asyncio=1.4.1=py_0
  - ninja=1.10.1=py37hfd86e86_0
  - notebook=6.1.4=py37hc8dfbb8_1
  - olefile=0.46=py37_0
  - openssl=1.1.1h=h516909a_0
  - packaging=20.4=pyh9f0ad1d_0
  - pandoc=2.11.0.2=hd18ef5c_0
  - pandocfilters=1.4.2=py_1
  - parso=0.7.1=pyh9f0ad1d_0
  - pexpect=4.8.0=pyh9f0ad1d_2
  - pickleshare=0.7.5=py_1003
  - pip=20.2.4=py37_0
  - prometheus_client=0.8.0=pyh9f0ad1d_0
  - prompt-toolkit=3.0.8=py_0
  - ptyprocess=0.6.0=py_1001
  - pycparser=2.20=pyh9f0ad1d_2
  - pygments=2.7.1=py_0
  - pyopenssl=19.1.0=py_1
  - pyparsing=2.4.7=pyh9f0ad1d_0
  - pyrsistent=0.17.3=py37h8f50634_1
  - pysocks=1.7.1=py37he5f6b98_2
  - python=3.7.9=h7579374_0
  - python-dateutil=2.8.1=py_0
  - python_abi=3.7=1_cp37m
  - pytorch=1.6.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - pyzmq=19.0.2=py37hac76be4_2
  - readline=8.0=h7b6447c_0
  - requests=2.24.0=pyh9f0ad1d_0
  - send2trash=1.5.0=py_0
  - setuptools=50.3.0=py37hb0f4dca_1
  - six=1.15.0=py_0
  - sqlite=3.33.0=h62c20be_0
  - terminado=0.9.1=py37hc8dfbb8_1
  - testpath=0.4.4=py_0
  - tk=8.6.10=hbc83047_0
  - torchvision=0.7.0=py37_cu101
  - tornado=6.0.4=py37h8f50634_2
  - traitlets=5.0.5=py_0
  - urllib3=1.25.11=py_0
  - wcwidth=0.2.5=pyh9f0ad1d_2
  - webencodings=0.5.1=py_1
  - wheel=0.35.1=py_0
  - xz=5.2.5=h7b6447c_0
  - zeromq=4.3.3=he1b5a44_2
  - zipp=3.3.1=py_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.5=h9ceee32_0
  - pip:
    - absl-py==0.10.0
    - cachetools==4.1.1
    - cycler==0.10.0
    - fsspec==0.8.4
    - future==0.18.2
    - google-auth==1.22.1
    - google-auth-oauthlib==0.4.1
    - grpcio==1.33.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.5.1
    - jupyter==1.0.0
    - jupyter-console==6.2.0
    - kiwisolver==1.2.0
    - markdown==3.3.2
    - matplotlib==3.3.2
    - numpy==1.19.2
    - oauthlib==3.1.0
    - pandas==1.1.3
    - pillow==8.0.1
    - protobuf==3.13.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pytorch-lightning==1.0.3
    - pytz==2020.1
    - pyyaml==5.3.1
    - qtconsole==4.7.7
    - qtpy==1.9.0
    - requests-oauthlib==1.3.0
    - rsa==4.6
    - scipy==1.5.3
    - seaborn==0.11.0
    - sentencepiece==0.1.91
    - tabulate==0.8.7
    - tensorboard==2.3.0
    - tensorboard-plugin-wit==1.7.0
    - torchtext==0.7.0
    - tqdm==4.50.2
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
